<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloServer.proto

namespace GPBMetadata;

class HelloServer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a1168656c6c6f5365727665722e70726f746f12097270635f7072" .
            "6f746f221c0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809221d0a0a48656c6c6f5265706c79120f0a076d6573736167651801" .
            "20012809221b0a0c48656c6c6f4d657373616765120b0a036d7367180120" .
            "012809328e010a0b48656c6c6f536572766572123c0a0853617948656c6c" .
            "6f12172e7270635f70726f746f2e48656c6c6f526571756573741a152e72" .
            "70635f70726f746f2e48656c6c6f5265706c79220012410a0b4765744865" .
            "6c6c6f4d736712172e7270635f70726f746f2e48656c6c6f526571756573" .
            "741a172e7270635f70726f746f2e48656c6c6f4d65737361676522006206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

